### ISSUE TITLE
only horizontal mode is available on Jolla C

### ISSUE THREAD

**Issue by atlochowski** [piggz/harbour-advanced-camera#17]
only horizontal mode is available on Jolla C

**Comment by piggz** [comment]
implemented

**Comment by atlochowski** [comment]
i'm not pretty sure if it's solved. 
When I have phone in portrait mode, phone acts like in horizontal mode. I can open top menu swiping from right egde, not from top edge. 
When I change phone orientation all indicator rotates which is good but phone act like in horizontal mode like I described before.
My phone Jolla C.

**Comment by tempura-san** [comment]
Same behaviour here on an Xperia X.
Seems like the phone is forced to landscape in the background, so all gestures are affected. 
Also the focus slider behaves strange when the phone is rotated from portrait to landscape.

**Comment by llelectronics** [comment]
Yes this is how it is implemented. The page does not rotate only the elements on the page rotate. 
Rotating the whole page is not advisable.

**Comment by jgibbon** [comment]
I agree this may need a better solution at some point. 
Even in landscape, it opens the app drawer instead of closing when the "wrong landscape" is used. Naturally, the content element rotation has to be (and look) a bit hacky for the current way of doing things (which I still do consider a good thing and an improvement for the amount of work that was necessary for it, btw).

jolla-camera gets this right by having its VideoOutput as an ApplicationWindow child and allowing the page to rotate how it wishes to. 
I guess really fixing it means a more significant gui rework partly outside of the scope of this specific issue, imho.

**Comment by piggz** [comment]
ill re-open for now, as i understant it better. its not related to landscape/portrait images, but to how the phone interaction works when rotated

**Comment by piggz** [comment]
Fixed in 0.6.0

**Comment by atlochowski** [comment]
thanks, now is perfect :)
