### ISSUE TITLE
Required icons

### ISSUE THREAD

**Issue by piggz** [piggz/harbour-advanced-camera#3]
Icons for the following functions are required:
scene-mode-values = auto,asd,landscape,snow,beach,sunset,night,portrait,backlight,sports,steadyphoto,flowers,candlelight,fireworks,party,night-portrait,theatre,action,AR,hdr

effect-values = none,mono,negative,solarize,sepia,posterize,whiteboard,blackboard,aqua,emboss,sketch,neon

**Comment by jgibbon** [comment]
Hi!
while I am almost sure that I won't be able to create many icons due to time constraints, I'd be glad to help out a bit. 
So even if someone else tackles these, it may be helpful to document some more context here:
 
 - Is there a preference for an **icon size**? Even with svg there can be different "detail" constraints or different line widths for different sizes. I'd guess "iconSizeMedium" would be a good start.
 - What exactly does the **AR mode** do? The only thing I could find was Android features (AR Stickers/3d models in videos) with the ARCore library and I somehow doubt that will be included…
- Initially I was a bit confused about "**asd**" (and thought it was just a "asdfgh" placeholder) before realizing it's "auto scene detection" when seeing that it was the old "**auto**" mode. No real question, but it would be nice to know how these modes differ to try to think of different icons for them. :) 

cheers!

**Comment by piggz** [comment]
Hi, thanks for the offer of help

Initially id like icons for each scene mode and color effect mode, that would make the UI a bit nicer.  I am using icon sizes of 72x72 currently.

AR mode is Augmented Reality ... it doesnt really do anything except change the exposure mode to something useful for AR.

ASD is actually what Auto should have been ... in the past, Auto was actually 'Off' !

**Comment by JSEHV** [comment]
Here is an new refreshed icon for the app. 
You can pick which one of the three you like most:

![harbour-advanced-camera-172x172](https://user-images.githubusercontent.com/5128988/54694111-fe135b80-4b27-11e9-910c-bb9751b1471f.png)
![harbour-advanced-camera-with-flash-172x172](https://user-images.githubusercontent.com/5128988/54694113-fe135b80-4b27-11e9-99fe-be5d9a62f2ab.png)
![harbour-advanced-camera-A-172x172](https://user-images.githubusercontent.com/5128988/54694112-fe135b80-4b27-11e9-95d1-439994908b93.png)

Worked them out in all sizes for all three variants needed for the app and as a .svg file:

[harbour-advanced-camera-icons.zip](https://github.com/piggz/harbour-advanced-camera/files/2988738/harbour-advanced-camera-icons.zip)

**Comment by jgibbon** [comment]
@piggz The first icon @JSEHV attached should really be used IMHO. Without the extra pictograms, it fits SFOS icon style "[minimalism + gradients](https://sailfishos.org/design/icons/)" quite nicely.

@JSEHV I encourage you to check out for example https://yangsu.github.io/pull-request-tutorial/ for an overview. I'm sure you can do it. I like how you improved on the current icon a lot while respecting the "colourful lens" theme of it.
cheers!

**Comment by JSEHV** [comment]
Somehow I can't publish the branch from GitHub desktop to harbour-advanced-camera

![Schermafbeelding 2019-03-28 om 16 01 22](https://user-images.githubusercontent.com/5128988/55168279-d5681300-5172-11e9-91c3-234aea4fc182.png)
